5.1 Getting_Started_with_Rails/practice/blog/config/routes.rb
Rails.application.routes.draw do


  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :users
  resources :articles, :categories, :authors

end

5.1 Getting_Started_with_Rails/practice/blog/app/models/admin.rb
class Admin < ApplicationRecord
  validate :can_access_18

  def can_access_18
    unless is_admin && age <18
      self.can_access = false
    end
    self.can_access = true
  end
end

5.1 Getting_Started_with_Rails/practice/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

5.1 Getting_Started_with_Rails/practice/blog/app/models/article.rb
class Article < ApplicationRecord
  has_and_belongs_to_many :categories
  belongs_to :author

  # validates :title, presence: true,
  #                   length: { minimum: 5 }
  # validates :text, presence: true,
  #                   length: { minimum: 10 }

end

5.1 Getting_Started_with_Rails/practice/blog/app/models/author.rb
class Author <  ApplicationRecord
  has_many :articles
end

5.1 Getting_Started_with_Rails/practice/blog/app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :articles
end

5.1 Getting_Started_with_Rails/practice/blog/app/models/user.rb
class User < ApplicationRecord

  # validates :firstname, :lastname, :email, :password, presence: true
  # validates :firstname, :lastname, length: { maximum: 25 }
  # validates :password, length: { maximum: 64 }

  # validates_each :email do |record, attribute, value|
  #   unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  #     record.errors.add(value, "is not an email")
  #   end
  # end

  # validates :password, confirmation: true


  # before_create do
  #   if firstname == "thien"
  #     self.lastname = "tran minh"
  #   end
  # end



end

5.1 Getting_Started_with_Rails/practice/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

5.1 Getting_Started_with_Rails/practice/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])

  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      @article.category_ids = params[:category_ids]
      # redirect_to article_path(id: @article.id)
      redirect_to articles_path

    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text, :gender,:author_id)
    end
end

5.1 Getting_Started_with_Rails/practice/blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
      @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])

  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to category_path(id: category.id)
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:type)
    end
end

5.1 Getting_Started_with_Rails/practice/blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    @users = User.all
  end

  # def show
  #   @user = User.find(params[:id])
  # end

  def new
    @user = User.new
  end

  # def edit
  #   @user = User.find(params[:id])
  # end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  # def update
  #   @user = User.find(params[:id])

  #   if @user.update(user_params)
  #     redirect_to @user
  #   else
  #     render 'edit'
  #   end
  # end

  # def destroy
  #   @user = User.find(params[:id])
  #   @user.destroy

  #   redirect_to articles_path
  # end

  private
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
    end

end

5.1 Getting_Started_with_Rails/practice/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

5.1 Getting_Started_with_Rails/practice/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

5.1 Getting_Started_with_Rails/practice/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

5.1 Getting_Started_with_Rails/practice/blog/app/helpers/users_helper.rb
module UsersHelper
end

5.1 Getting_Started_with_Rails/practice/blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

5.1 Getting_Started_with_Rails/practice/blog/app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text, "Description" %><br>
    <%= form.text_area :text %>
  </p>

    <p>
     Active   <%= radio_button("article","active","active") %>
     Inactive <%= radio_button("article","active","inactive") %>
    </p>


    <p>
      Categories <br>
      Music <%= check_box("category", "music") %><br>
      Post  <%= check_box("category", "post") %><br>
      Story <%= check_box("category", "story") %>
    </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

5.1 Getting_Started_with_Rails/practice/blog/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for @article do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text, "Description" %><br>
    <%= form.text_area :text %>
  </p>

  <p>

   Male <%=  radio_button("article", "gender", "male") %>
   Female <%=  radio_button("article", "gender", "female") %>

  </p>

  <p>
  <% Category.all.each do |c| %>
    <%= c.name %>
    <%= check_box_tag "category_ids[]", c.id %>
  <% end %>
  </p>

  <p>
  <%= select("article", "author_id", Author.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }) %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

5.1 Getting_Started_with_Rails/practice/blog/app/views/articles/index.html.slim
<!-- <h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              # method: :delete,
              # data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table> -->

h1 Listing Articles
= link_to 'New articles', new_article_path
table
  tr
    th Title
    th Description
    th Author
    th Gender
    th colspan="3"

  - @articles.each do |article|
    tr
      td = article.title
      td = article.text
      td = article.author_id
      td = article.gender
      td = link_to 'Show', article_path(article)
      td = link_to 'Edit', edit_article_path(article)
      td = link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' }
  end

5.1 Getting_Started_with_Rails/practice/blog/app/views/articles/new.html.erb
<h1>New Articles</h1>

<%= form_for @article do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text, "Description" %><br>
    <%= form.text_area :text %>
  </p>

  <p>
   Active   <%= radio_button("article","active","active") %>
   Inactive <%= radio_button("article","active","inactive") %>
  </p>

  <p>

    <%= check_box_tag "category_ids", '1' %>
    <%= check_box_tag "category_ids", '2' %>
    <%= check_box_tag "category_ids", '3' %>

  </p>

  <%= select("article", "author_id", Author.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }) %>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

5.1 Getting_Started_with_Rails/practice/blog/app/views/articles/show.html.erb
<%= params.inspect %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>



<%= link_to 'Back', articles_path %>

5.1 Getting_Started_with_Rails/practice/blog/app/views/categories/new.html.erb
<%= form_for @category do |form| %>

Music  <%= check_box("category", "music") %>
Post   <%= check_box("category", "post") %>
Story  <%= check_box("category", "story") %>
<% end %>

5.1 Getting_Started_with_Rails/practice/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

5.1 Getting_Started_with_Rails/practice/blog/app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>

  <p>
    <%= form.label :firstname %><br>
    <%= form.text_field :firstname %>
  </p>

  <p>
    <%= form.label :lastname %><br>
    <%= form.text_field :lastname %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.text_field :password %>
  </p>

  <p>
    <%= form.label :confirmpassword %><br>
    <%= form.text_field :password_confirmation %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

5.1 Getting_Started_with_Rails/practice/blog/app/views/users/new.html.erb
<h1>New Users</h1>

<%= form_with model: @user, url: users_path, local: true do |form| %>


  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :firstname %><br>
    <%= form.text_field :firstname %>
  </p>

  <p>
    <%= form.label :lastname %><br>
    <%= form.text_field :lastname %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label  :password %><br>
    <%= form.text_field :password %>
  </p>

  <p>
    <%= form.label :password_confirmation %><br>
    <%= form.text_field :password_confirmation %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

5.1 Getting_Started_with_Rails/practice/blog/app/views/welcome/index.html.slim
= params.inspect